apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 339712930646.dkr.ecr.us-east-1.amazonaws.com/mysql-ecr:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pw
              key: password
        ports:
        - containerPort: 3306
      imagePullSecrets:
      - name: ecr-registry-secret
