apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 339712930646.dkr.ecr.us-east-1.amazonaws.com/mysql-ecr:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-root-pw
          key: password
    ports:
    - containerPort: 3306
  imagePullSecrets:
  - name: ecr-registry-secret

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306