apiVersion: v1
kind: Pod
metadata:
  name: employees-pod
  labels:
    app: employees
spec:
  containers:
  - name: employees
    image: 339712930646.dkr.ecr.us-east-1.amazonaws.com/webapp-ecr:latest
    ports:
    - containerPort: 8080
    env:
    - name: DBPORT
      value: "3306"
    - name: DBHOST
      value: "mysql-db" 
    - name: DATABASE
      value: "employees"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      valueFrom:
        secretKeyRef:
          name: mysql-root-pw
          key: password
    - name: PORT
      value: "8080"
  imagePullSecrets:
  - name: ecr-registry-secret
