apiVersion: v1
kind: ReplicaSet
metadata:
  name: employees-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: employees
        image: 339712930646.dkr.ecr.us-east-1.amazonaws.com/mysql-ecr:latest
        ports:
        - containerPort: 8080