apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 339712930646.dkr.ecr.us-east-1.amazonaws.com/webapp-ecr:v2
        ports:
        - containerPort: 8080
        env:
        - name: DBPORT
          value: "3306"
        - name: DBHOST
          value: "mysql-db" 
        - name: DATABASE
          value: "employees"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mysql-root-pw
              key: password
      imagePullSecrets:
      - name: ecr-registry-secret
